export const INITIALIZE = 'INITIALIZE';

export const WRITE_POST_START = 'WRITE_POST_START';
export const WRITE_POST_SUCCESS = 'WRITE_POST_SUCCESS';
export const WRITE_POST_FAIL = 'WRITE_POST_FAIL';

export const CHANGE_INPUT = 'CHANGE_INPUT';
export const CHANGE_FILE = 'CHANGE_FILE';

export const GET_POST_START = 'GET_POST_START';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';

export const GET_POST_LIST_START = 'GET_POST_LIST_START';
export const GET_POST_LIST_SUCCESS = 'GET_POST_LIST_SUCCESS';
export const GET_POST_LIST_FAIL = 'GET_POST_LIST_FAIL';

export const REMOVE_POST_START = 'REMOVE_POST_START';
export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS';
export const REMOVE_POST_FAIL = 'REMOVE_POST_FAIL';

export const EDITOR_GET_POST_START = 'EDITOR_GET_POST_START';
export const EDITOR_GET_POST_SUCCESS = 'EDITOR_GET_POST_SUCCESS';
export const EDITOR_GET_POST_FAIL = 'EDITOR_GET_POST_FAIL';

export const EDIT_POST_START = 'EDIT_POST_START';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_POST_LIST_SUCCESS = 'SET_POST_LIST_SUCCESS';