export const INITIALIZE = 'INITIALIZE';

export const WRITE_POST_START = 'WRITE_POST_START';
export const WRITE_POST_SUCCESS = 'WRITE_POST_SUCCESS';
export const WRITE_POST_FAIL = 'WRITE_POST_FAIL';

export const CHANGE_INPUT = 'CHANGE_INPUT';
export const CHANGE_FILE = 'CHANGE_FILE';

export const GET_POST_START = 'GET_POST_START';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';

export const GET_POST_LIST_START = 'GET_POST_LIST_START';
export const GET_POST_LIST_SUCCESS = 'GET_POST_LIST_SUCCESS';
export const GET_POST_LIST_FAIL = 'GET_POST_LIST_FAIL';